services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    WEM\AudioTracksBundle\:
        resource: ../src/
        exclude: ../src/{ContaoManager,DependencyInjection,Model,Util}


    wem.audiotracks.rss_feed:
        class: WEM\AudioTracksBundle\Classes\RssFeed
        arguments:
            $framework: '@contao.framework'
        public: true

    WEM\AudioTracksBundle\Cron\PurgeTrackingDataCron:
        arguments:
            $retentionMonths: '%wem_audiotracks.retention_months%'

    WEM\AudioTracksBundle\Migration\DurationMigration:
        arguments:
            $projectDir: '%kernel.project_dir%'
